version: "3.8"
services:
  opmc_main_db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=opmc
      - POSTGRES_PASSWORD=opmc
      - POSTGRES_DB=opmc_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  opmc_main_redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
